// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

//! Turn the workspace-root `runtime-deps.toml` pins into Rust constants.
//!
//! Every `[runtime.<name>]` field becomes a `pub const <NAME>_<FIELD>: &str`
//! written to `$OUT_DIR/pins.rs`, which `src/lib.rs` includes. Generating at
//! build time (rather than committing a generated source file) means the pin
//! exists exactly once in the tree, so there is nothing to drift and no
//! `--check` gate to keep honest; a missing or malformed pin is a build error.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

/// Pin file, relative to this crate's manifest directory.
const PINS_FILE: &str = "../../runtime-deps.toml";

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let pins_path = manifest_dir.join(PINS_FILE);
    println!("cargo:rerun-if-changed={}", pins_path.display());

    let text = fs::read_to_string(&pins_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", pins_path.display()));
    let generated = render(&text, &pins_path);

    let out_path =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo")).join("pins.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

/// Render the constants for one pin file. Panics with a pointed message on any
/// schema violation so a bad pin fails the build instead of the runtime.
fn render(text: &str, path: &Path) -> String {
    let doc: toml::Value = toml::from_str(text)
        .unwrap_or_else(|err| panic!("{} is not valid TOML: {err}", path.display()));
    let runtimes = doc
        .get("runtime")
        .and_then(toml::Value::as_table)
        .unwrap_or_else(|| panic!("{} must define a [runtime] table", path.display()));

    let mut out = String::from(
        "// @generated by build.rs from runtime-deps.toml -- do not edit; edit the pin file.\n",
    );
    for (name, entry) in runtimes {
        let fields = entry
            .as_table()
            .unwrap_or_else(|| panic!("[runtime.{name}] must be a table of string fields"));
        for (field, value) in fields {
            let literal = value
                .as_str()
                .unwrap_or_else(|| panic!("runtime.{name}.{field} must be a string"));
            assert!(
                !literal.contains(['"', '\\']),
                "runtime.{name}.{field} must not contain quotes or backslashes"
            );
            let ident = format!("{}_{}", const_ident(name), const_ident(field));
            writeln!(
                out,
                "/// `runtime.{name}.{field}` from `runtime-deps.toml`.\n\
                 pub const {ident}: &str = \"{literal}\";"
            )
            .expect("writing to a String cannot fail");
        }
    }
    out
}

/// `rocm-abi` -> `ROCM_ABI`: upper-case, with separators folded to `_`.
fn const_ident(raw: &str) -> String {
    raw.to_uppercase().replace(['-', '.'], "_")
}
