// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

//! Replacing ComfyUI's code in an existing `source/` folder without touching
//! anything else there.
//!
//! `rocm comfyui start` runs ComfyUI from `source/` without
//! `--user-directory`, `--output-directory` or `--input-directory`, so ComfyUI
//! keeps the user's models, saved workflows, outputs and uploads inside it, and
//! users keep other things there too (a `.git` checkout, a `venv/`,
//! `styles.csv`, logs). A reinstall therefore removes only what a ComfyUI
//! release shipped, moves the new release in around everything else, and
//! never moves, copies or deletes anything under a
//! [`PRESERVED_SOURCE_ENTRIES`] entry.
//!
//! Which top-level names a release shipped is recorded in
//! [`RELEASE_RECORD`] when it is installed, and a reinstall removes those. An
//! entry of the user's that has the name of something the new release adds is
//! renamed out of the way (see [`SwapReport::set_aside`]), not removed. An
//! install that predates the record has nothing to tell release code from the
//! user's, so the names the new release ships are removed there and listed
//! (see [`SwapReport::replaced`]). Every other entry is left in place and
//! reported.
//!
//! The code swap is not atomic, but code can be fetched again: a marker file
//! records an unfinished swap, `start` refuses to run a half-replaced tree,
//! and running the swap again finishes it. `main.py` is removed first and
//! moved in last, so a half-replaced tree never looks complete.

use anyhow::{Context, Result, bail};
use std::collections::BTreeSet;
use std::ffi::{OsStr, OsString};
use std::fmt;
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};

/// Entries of the ComfyUI `source/` folder that hold the user's own content
/// and that a reinstall leaves in place.
///
/// `models` (the folder `rocm comfyui models-path` reports), `user` (saved
/// workflows and settings), `output` (generated images; ComfyUI also saves
/// models there), `input` (uploaded images), `custom_nodes` (third-party nodes
/// the user installed, often with their own settings or weights inside),
/// `datasets` (training data; ComfyUI's `folder_paths.py` registers it under
/// the same base folder) and `extra_model_paths.yaml` (user-written; the
/// release ships only the `.example`).
pub(super) const PRESERVED_SOURCE_ENTRIES: &[&str] = &[
    "models",
    "user",
    "output",
    "input",
    "custom_nodes",
    "datasets",
    "extra_model_paths.yaml",
];

/// Written into `source/` before the code swap starts and removed when it
/// finishes. Its presence means a swap was interrupted. It records the
/// [`PRESERVED_SOURCE_ENTRIES`] that existed before that swap began (so a
/// re-run reports what was really the user's rather than what the interrupted
/// run may already have added from the release), the names of the release
/// that run was installing, and the entries of the user's it set aside (so a
/// re-run neither mistakes that release's code for the user's nor the user's
/// entry for release code).
pub(super) const SWAP_MARKER: &str = ".rocm-cli-reinstall-in-progress";

/// The top-level names the installed release shipped, one per line, written
/// with every install. It is what a later reinstall removes.
pub(super) const RELEASE_RECORD: &str = ".rocm-cli-release-entries";

/// Prefix of every file this module writes into `source/`. Such files are
/// never reported as the user's, and a leftover copy in progress is removed.
const CLI_FILE_PREFIX: &str = ".rocm-cli-";
const COPY_IN_PROGRESS_PREFIX: &str = ".rocm-cli-copy-";

/// Inserted between a set-aside entry's name and a timestamp.
pub(super) const SET_ASIDE_INFIX: &str = ".rocm-cli-kept-";

/// Generated by Python from the release's own code, so they go with it.
const GENERATED_FROM_RELEASE: &[&str] = &["__pycache__"];

/// The entry ComfyUI is started from. Removed first and moved in last, so a
/// tree whose swap was cut short never has it.
const ENTRY_POINT: &str = "main.py";

/// Marker lines that are not a preserved entry's name.
const MARKER_RELEASE: &str = "release\t";
const MARKER_SET_ASIDE: &str = "set-aside\t";

/// What a swap did with the existing folder's entries.
#[derive(Debug, Default, PartialEq, Eq)]
pub(super) struct SwapReport {
    /// [`PRESERVED_SOURCE_ENTRIES`] the folder held before the swap began.
    pub(super) kept: Vec<&'static str>,
    /// Top-level entries removed in an install with no usable
    /// [`RELEASE_RECORD`]. Nothing there tells the user's entry from release
    /// code of the same name, so the user is told what went.
    pub(super) replaced: Vec<String>,
    /// Entries of the user's (`(name, new name)`) whose name the new release
    /// started shipping, renamed rather than removed.
    pub(super) set_aside: Vec<(String, String)>,
    /// Top-level entries no ComfyUI release shipped, left exactly as they were.
    pub(super) left_in_place: Vec<String>,
    /// Problems that did not stop the swap but that the user should hear about.
    pub(super) warnings: Vec<String>,
}

/// A release entry that could not be removed, which leaves the swap
/// unfinished. Typed so the caller can name the command that finishes it.
#[derive(Debug)]
pub(super) struct RemovalFailed {
    pub(super) path: PathBuf,
    error: io::Error,
}

impl fmt::Display for RemovalFailed {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "failed to remove {} ({}); close any program using it",
            self.path.display(),
            self.error
        )
    }
}

impl std::error::Error for RemovalFailed {}

/// The [`PRESERVED_SOURCE_ENTRIES`] `source` holds now, in their listed order.
pub(super) fn preserved_entries_present(source: &Path) -> Vec<&'static str> {
    PRESERVED_SOURCE_ENTRIES
        .iter()
        .copied()
        .filter(|name| fs::symlink_metadata(source.join(name)).is_ok())
        .collect()
}

/// What a reinstall started now would report as kept: the entries an
/// interrupted swap recorded, or else the ones present.
pub(super) fn planned_kept(source: &Path) -> Vec<&'static str> {
    if swap_interrupted(source) {
        read_marker(&source.join(SWAP_MARKER)).0.kept
    } else {
        preserved_entries_present(source)
    }
}

/// Whether `source` has a readable record of what its release shipped, which
/// decides whether a reinstall sets aside or replaces an entry named like new
/// release code.
pub(super) fn has_release_record(source: &Path) -> bool {
    read_release_record(source).0.is_some()
}

/// Whether a code swap into `source` was started and did not finish.
pub(super) fn swap_interrupted(source: &Path) -> bool {
    fs::symlink_metadata(source.join(SWAP_MARKER)).is_ok()
}

/// Installs the unpacked release at `new_tree` into `source`.
///
/// Without an existing `source` the release tree is simply moved there. With
/// one, entries of the user's named like new release code are set aside, the
/// entries a ComfyUI release shipped are removed (`main.py` first), the new
/// release's are moved in (`main.py` last), and inside each preserved folder
/// the release only adds what is missing (see [`add_missing_entries`]).
/// Preserved entries, and every entry no release shipped, are never moved,
/// copied, overwritten, deleted or written through when they are symlinks.
pub(super) fn install_release_tree(new_tree: &Path, source: &Path) -> Result<SwapReport> {
    install_release_tree_with(new_tree, source, &mut |_| Ok(()))
}

/// [`install_release_tree`] with `step` called before every filesystem
/// change, so a test can stop the swap at any point the way a crash or a
/// killed process would: without any cleanup running afterwards.
fn install_release_tree_with(
    new_tree: &Path,
    source: &Path,
    step: &mut dyn FnMut(&Path) -> io::Result<()>,
) -> Result<SwapReport> {
    install_release_tree_removing_with(new_tree, source, step, &remove_path_io)
}

/// [`install_release_tree_with`] with the removal of a release entry
/// injectable too, so a test can make it fail the way a file held open by
/// another program does, whoever runs the test.
fn install_release_tree_removing_with(
    new_tree: &Path,
    source: &Path,
    step: &mut dyn FnMut(&Path) -> io::Result<()>,
    remove: &dyn Fn(&Path) -> io::Result<()>,
) -> Result<SwapReport> {
    let new_names = release_names(new_tree)?;
    if fs::symlink_metadata(source).is_err() {
        let parent = source
            .parent()
            .context("ComfyUI source path has no parent directory")?;
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
        // Recorded inside the tree before it moves, so the one rename that
        // installs the release also installs its record.
        write_atomically(
            &new_tree.join(RELEASE_RECORD),
            &join_lines(&new_names),
            step,
        )?;
        move_release_entry(new_tree, source, step)?;
        return Ok(SwapReport::default());
    }
    if !source.is_dir() {
        bail!("{} exists but is not a folder", source.display());
    }

    let mut report = SwapReport::default();
    let marker = source.join(SWAP_MARKER);
    let mut plan = if swap_interrupted(source) {
        let (plan, warning) = read_marker(&marker);
        report.warnings.extend(warning);
        plan
    } else {
        SwapPlan {
            kept: preserved_entries_present(source),
            ..SwapPlan::default()
        }
    };
    report.kept.clone_from(&plan.kept);
    let (recorded, record_warnings) = read_release_record(source);
    report.warnings.extend(record_warnings);

    // With a record, an entry named like something the new release adds that
    // neither the installed release nor an interrupted run's release shipped
    // is the user's, and is set aside. That is decided before anything of the
    // new release is moved in, and written to the marker before the entry is
    // renamed, so a re-run can tell the two apart.
    if let Some(recorded) = &recorded {
        for name in &new_names {
            let known = recorded.contains(name)
                || plan.release.contains(name)
                || plan.set_aside.iter().any(|(planned, _)| planned == name);
            if !known && fs::symlink_metadata(source.join(name)).is_ok() {
                let new_name = set_aside_name(source, name, &plan, unix_seconds());
                plan.set_aside.push((name.clone(), new_name));
            }
        }
    }
    plan.release.extend(new_names.iter().cloned());
    write_atomically(&marker, &plan.render(), step)?;
    for (name, new_name) in &plan.set_aside {
        let (from, to) = (source.join(name), source.join(new_name));
        if fs::symlink_metadata(&to).is_err() && fs::symlink_metadata(&from).is_ok() {
            step(&from)?;
            rename_with_retry(&from, &to).with_context(|| {
                format!("failed to move {} to {}", from.display(), to.display())
            })?;
        }
        if fs::symlink_metadata(&to).is_ok() {
            report.set_aside.push((
                name.to_string_lossy().into_owned(),
                new_name.to_string_lossy().into_owned(),
            ));
        }
    }

    // What a ComfyUI release shipped here: the installed release's recorded
    // names, plus the new release's and an interrupted run's (which also
    // covers whatever part of them that run already moved in, and an install
    // from before the record existed).
    let mut release_owned: BTreeSet<OsString> = plan.release.clone();
    release_owned.extend(recorded.iter().flatten().cloned());
    release_owned.extend(GENERATED_FROM_RELEASE.iter().map(OsString::from));

    let mut to_remove = Vec::new();
    for entry in read_dir(source)? {
        let name = entry.file_name();
        let text = name.to_string_lossy();
        if is_preserved(&name)
            || text == SWAP_MARKER
            || text == RELEASE_RECORD
            || plan.set_aside.iter().any(|(_, new_name)| *new_name == name)
        {
            continue;
        }
        if release_owned.contains(&name) {
            if recorded.is_none() {
                report.replaced.push(text.clone().into_owned());
            }
            to_remove.push(entry.path());
        } else if text.starts_with(COPY_IN_PROGRESS_PREFIX) {
            to_remove.push(entry.path());
        } else if !text.starts_with(CLI_FILE_PREFIX) {
            report.left_in_place.push(text.into_owned());
        }
    }
    report.replaced.sort();
    report.left_in_place.sort();
    to_remove.sort_by_key(|path| !path.ends_with(ENTRY_POINT));
    for path in to_remove {
        step(&path)?;
        remove(&path).map_err(|error| RemovalFailed {
            path: path.clone(),
            error,
        })?;
    }

    let mut incoming = read_dir(new_tree)?;
    incoming.sort_by_key(|entry| entry.file_name() == ENTRY_POINT);
    for entry in incoming {
        let name = entry.file_name();
        let target = source.join(&name);
        if is_preserved(&name) {
            if fs::symlink_metadata(&target).is_err() {
                move_release_entry(&entry.path(), &target, step)?;
            } else {
                add_missing_entries(&entry.path(), &target, step)?;
            }
        } else if !name.to_string_lossy().starts_with(CLI_FILE_PREFIX) {
            move_release_entry(&entry.path(), &target, step)?;
        }
    }

    write_atomically(&source.join(RELEASE_RECORD), &join_lines(&new_names), step)?;
    step(&marker)?;
    fs::remove_file(&marker).with_context(|| format!("failed to remove {}", marker.display()))?;
    Ok(report)
}

/// What the [`SWAP_MARKER`] records; see there.
#[derive(Debug, Default)]
struct SwapPlan {
    kept: Vec<&'static str>,
    release: BTreeSet<OsString>,
    set_aside: Vec<(OsString, OsString)>,
}

impl SwapPlan {
    fn render(&self) -> String {
        let mut lines: Vec<String> = self.kept.iter().map(|name| (*name).to_owned()).collect();
        lines.extend(
            self.release
                .iter()
                .map(|name| format!("{MARKER_RELEASE}{}", name.to_string_lossy())),
        );
        lines.extend(self.set_aside.iter().map(|(name, new_name)| {
            format!(
                "{MARKER_SET_ASIDE}{}\t{}",
                name.to_string_lossy(),
                new_name.to_string_lossy()
            )
        }));
        lines.join("\n")
    }

    fn parse(text: &str) -> Self {
        let mut plan = Self {
            kept: PRESERVED_SOURCE_ENTRIES
                .iter()
                .copied()
                .filter(|name| text.lines().any(|line| line == *name))
                .collect(),
            ..Self::default()
        };
        for line in text.lines() {
            if let Some(name) = line.strip_prefix(MARKER_RELEASE) {
                if is_single_entry_name(name) {
                    plan.release.insert(OsString::from(name));
                }
            } else if let Some((name, new_name)) = line
                .strip_prefix(MARKER_SET_ASIDE)
                .and_then(|rest| rest.split_once('\t'))
                && is_single_entry_name(name)
                && is_single_entry_name(new_name)
            {
                plan.set_aside
                    .push((OsString::from(name), OsString::from(new_name)));
            }
        }
        plan
    }
}

fn unix_seconds() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// `<name>.rocm-cli-kept-<seconds>`, with a counter added if that is taken in
/// `source` or by another entry this swap sets aside.
fn set_aside_name(source: &Path, name: &OsStr, plan: &SwapPlan, seconds: u64) -> OsString {
    let mut counter = 1;
    loop {
        let mut candidate = name.to_os_string();
        candidate.push(format!("{SET_ASIDE_INFIX}{seconds}"));
        if counter > 1 {
            candidate.push(format!("-{counter}"));
        }
        let taken = fs::symlink_metadata(source.join(&candidate)).is_ok()
            || plan
                .set_aside
                .iter()
                .any(|(_, planned)| *planned == candidate);
        if !taken {
            return candidate;
        }
        counter += 1;
    }
}

fn is_preserved(name: &OsStr) -> bool {
    PRESERVED_SOURCE_ENTRIES
        .iter()
        .any(|preserved| name == *preserved)
}

/// The release's own top-level names, without the preserved ones.
fn release_names(tree: &Path) -> Result<Vec<OsString>> {
    let mut names: Vec<OsString> = read_dir(tree)?
        .into_iter()
        .map(|entry| entry.file_name())
        .filter(|name| !is_preserved(name) && !name.to_string_lossy().starts_with(CLI_FILE_PREFIX))
        .collect();
    names.sort();
    Ok(names)
}

fn join_lines(names: &[OsString]) -> String {
    names
        .iter()
        .map(|name| name.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n")
}

/// Whether `line` names a single entry directly inside `source/`: not empty,
/// `.`, `..`, an absolute path or a path with more than one part.
fn is_single_entry_name(line: &str) -> bool {
    let mut components = Path::new(line).components();
    matches!(
        (components.next(), components.next()),
        (Some(Component::Normal(_)), None)
    )
}

/// The installed release's recorded names, or `None` when there is no usable
/// record: none at all (an install from before it existed, which is not a
/// problem) or an unreadable one, which is reported. A line that does not
/// name a single entry of `source/` is ignored and reported.
fn read_release_record(source: &Path) -> (Option<Vec<OsString>>, Vec<String>) {
    let path = source.join(RELEASE_RECORD);
    match fs::read_to_string(&path) {
        Ok(text) => {
            let mut names = Vec::new();
            let mut warnings = Vec::new();
            for line in text.lines().filter(|line| !line.is_empty()) {
                if !is_single_entry_name(line) {
                    warnings.push(format!(
                        "ignored {line:?} in {}: it does not name an entry of that folder",
                        path.display()
                    ));
                } else if !is_preserved(OsStr::new(line)) {
                    names.push(OsString::from(line));
                }
            }
            (Some(names), warnings)
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => (None, Vec::new()),
        Err(error) => (
            None,
            vec![format!(
                "could not read {} ({error}); entries with the names the new release ships \
                 were replaced instead",
                path.display()
            )],
        ),
    }
}

fn read_dir(path: &Path) -> Result<Vec<fs::DirEntry>> {
    fs::read_dir(path)
        .with_context(|| format!("failed to read {}", path.display()))?
        .collect::<io::Result<Vec<_>>>()
        .with_context(|| format!("failed to read {}", path.display()))
}

/// What an interrupted swap recorded. An unreadable marker yields an empty
/// plan and a warning. That can only make a re-run remove less: an entry the
/// interrupted run moved in is then set aside instead, never deleted.
fn read_marker(marker: &Path) -> (SwapPlan, Option<String>) {
    match fs::read_to_string(marker) {
        Ok(text) => (SwapPlan::parse(&text), None),
        Err(error) => (
            SwapPlan::default(),
            Some(format!(
                "could not read {} ({error}); which of your folders were there before the \
                 interrupted reinstall is unknown, but none of them was touched",
                marker.display()
            )),
        ),
    }
}

/// Writes `path` through a temporary sibling and a rename, so a reader sees
/// either the old contents or the whole new ones.
fn write_atomically(
    path: &Path,
    contents: &str,
    step: &mut dyn FnMut(&Path) -> io::Result<()>,
) -> Result<()> {
    let mut temp_name = OsString::from(COPY_IN_PROGRESS_PREFIX);
    temp_name.push(path.file_name().context("path has no file name")?);
    let temp = path.with_file_name(temp_name);
    step(path)?;
    fs::write(&temp, contents).with_context(|| format!("failed to write {}", temp.display()))?;
    rename_with_retry(&temp, path).with_context(|| format!("failed to write {}", path.display()))
}

/// Moves each release entry under `release` that `into` lacks, recursing
/// where both hold a real (not symlinked) directory of the same name. Entries
/// `into` already has are left alone, so the user's copy wins, and a symlinked
/// folder of the user's is never written into: a model folder new in a
/// release appears, but nothing of the user's changes.
fn add_missing_entries(
    release: &Path,
    into: &Path,
    step: &mut dyn FnMut(&Path) -> io::Result<()>,
) -> Result<()> {
    if !is_real_dir(release) || !is_real_dir(into) {
        return Ok(());
    }
    for entry in read_dir(release)? {
        let target = into.join(entry.file_name());
        if fs::symlink_metadata(&target).is_err() {
            move_release_entry(&entry.path(), &target, step)?;
        } else {
            add_missing_entries(&entry.path(), &target, step)?;
        }
    }
    Ok(())
}

fn is_real_dir(path: &Path) -> bool {
    fs::symlink_metadata(path).is_ok_and(|metadata| metadata.is_dir())
}

/// Moves a release entry into `source`. Only release content goes through
/// here — never the user's. A rename is all it takes unless the staging folder
/// and `source` are on different filesystems (`source` itself symlinked
/// elsewhere). Only then is the entry copied, without following symlinks, to a
/// temporary name that is renamed into place once complete, so a crash never
/// leaves a truncated release file under the real name.
fn move_release_entry(
    from: &Path,
    to: &Path,
    step: &mut dyn FnMut(&Path) -> io::Result<()>,
) -> Result<()> {
    move_release_entry_with(from, to, step, &rename_with_retry)
}

/// [`move_release_entry`] with the rename injectable, so a test can take the
/// copy path without a second filesystem.
fn move_release_entry_with(
    from: &Path,
    to: &Path,
    step: &mut dyn FnMut(&Path) -> io::Result<()>,
    rename: &dyn Fn(&Path, &Path) -> io::Result<()>,
) -> Result<()> {
    step(to)?;
    match rename(from, to) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::CrossesDevices => {
            let mut temp_name = OsString::from(COPY_IN_PROGRESS_PREFIX);
            temp_name.push(to.file_name().context("path has no file name")?);
            let temp = to.with_file_name(temp_name);
            remove_path(&temp)?;
            if let Err(copy_error) = copy_tree_no_follow(from, &temp) {
                remove_path(&temp).ok();
                return Err(copy_error);
            }
            rename(&temp, to).with_context(|| {
                format!("failed to move {} to {}", temp.display(), to.display())
            })?;
            remove_path(from)
        }
        Err(error) => Err(error)
            .with_context(|| format!("failed to move {} to {}", from.display(), to.display())),
    }
}

/// `fs::rename`, retried briefly on Windows while another program holds the
/// file: a scanner that opens freshly unpacked files holds them for a moment.
fn rename_with_retry(from: &Path, to: &Path) -> io::Result<()> {
    #[cfg(windows)]
    {
        let mut delay = std::time::Duration::from_millis(50);
        for _ in 0..5 {
            match fs::rename(from, to) {
                Err(error) if is_held_by_another_program(&error) => {
                    std::thread::sleep(delay);
                    delay *= 2;
                }
                result => return result,
            }
        }
    }
    fs::rename(from, to)
}

/// Access denied, or a sharing or lock violation (`ERROR_SHARING_VIOLATION`,
/// `ERROR_LOCK_VIOLATION`), which std reports with no specific error kind.
#[cfg(windows)]
fn is_held_by_another_program(error: &io::Error) -> bool {
    error.kind() == io::ErrorKind::PermissionDenied || matches!(error.raw_os_error(), Some(32 | 33))
}

/// Copies `from` to `to`, recreating symlinks as symlinks instead of copying
/// what they point at.
fn copy_tree_no_follow(from: &Path, to: &Path) -> Result<()> {
    let file_type = fs::symlink_metadata(from)
        .with_context(|| format!("failed to stat {}", from.display()))?
        .file_type();
    if file_type.is_symlink() {
        let target =
            fs::read_link(from).with_context(|| format!("failed to read {}", from.display()))?;
        return create_symlink(&target, from, to)
            .with_context(|| format!("failed to recreate the symlink {}", to.display()));
    }
    if file_type.is_dir() {
        fs::create_dir(to).with_context(|| format!("failed to create {}", to.display()))?;
        for entry in read_dir(from)? {
            copy_tree_no_follow(&entry.path(), &to.join(entry.file_name()))?;
        }
        return Ok(());
    }
    fs::copy(from, to)
        .map(|_| ())
        .with_context(|| format!("failed to copy {} to {}", from.display(), to.display()))
}

#[cfg(unix)]
fn create_symlink(target: &Path, _original: &Path, link: &Path) -> io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(windows)]
fn create_symlink(target: &Path, original: &Path, link: &Path) -> io::Result<()> {
    if fs::metadata(original).is_ok_and(|metadata| metadata.is_dir()) {
        std::os::windows::fs::symlink_dir(target, link)
    } else {
        std::os::windows::fs::symlink_file(target, link)
    }
}

/// Removes a file, symlink or directory tree; a missing path is not an error.
/// A symlink is removed itself, never what it points at.
fn remove_path(path: &Path) -> Result<()> {
    remove_path_io(path).with_context(|| format!("failed to remove {}", path.display()))
}

fn remove_path_io(path: &Path) -> io::Result<()> {
    let file_type = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata.file_type(),
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
    };
    if file_type.is_dir() {
        fs::remove_dir_all(path)
    } else {
        // A directory symlink on Windows is removed with `remove_dir`.
        fs::remove_file(path).or_else(|error| fs::remove_dir(path).map_err(|_| error))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TestDir(PathBuf);

    impl TestDir {
        fn new(name: &str) -> Self {
            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let root = std::env::temp_dir().join(format!(
                "rocm-cli-comfyui-swap-{name}-{}-{nonce}",
                std::process::id()
            ));
            fs::create_dir_all(&root).expect("create test root");
            Self(root)
        }
    }

    impl Drop for TestDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn write(root: &Path, files: &[(&str, &str)]) {
        for (relative, contents) in files {
            let path = root.join(relative);
            fs::create_dir_all(path.parent().expect("parent")).expect("create parent");
            fs::write(&path, contents).expect("write fixture");
        }
    }

    fn read(path: &Path) -> Option<String> {
        fs::read_to_string(path).ok()
    }

    /// The user's content: one file in every preserved entry, plus the
    /// user's own copy of a file the release also ships.
    const USER_FILES: [(&str, &str); 8] = [
        ("models/checkpoints/my-model.safetensors", "user model"),
        ("user/default/workflows/my-workflow.json", "user workflow"),
        ("output/ComfyUI_00001_.png", "user image"),
        ("input/my-upload.png", "user upload"),
        ("custom_nodes/my-node/__init__.py", "user node"),
        ("datasets/my-set/0001.png", "user dataset"),
        ("extra_model_paths.yaml", "user model paths"),
        (
            "custom_nodes/websocket_image_save.py",
            "user's edited sample",
        ),
    ];

    /// What users keep at the top of `source/` that no release ships.
    const UNKNOWN_FILES: [(&str, &str); 5] = [
        (".git/HEAD", "ref: refs/heads/master"),
        ("venv/pyvenv.cfg", "home = /usr"),
        ("styles.csv", "name,prompt"),
        ("comfyui.log", "log"),
        ("temp/preview.png", "scratch"),
    ];
    const UNKNOWN_NAMES: [&str; 5] = [".git", "comfyui.log", "styles.csv", "temp", "venv"];

    const OLD_RELEASE: [(&str, &str); 5] = [
        ("main.py", "old main"),
        ("comfy/dropped_file.py", "old code"),
        ("dropped_upstream.py", "old code"),
        ("__pycache__/dropped_upstream.cpython-312.pyc", "bytecode"),
        ("models/checkpoints/put_checkpoints_here", ""),
    ];

    const NEW_RELEASE: [(&str, &str); 7] = [
        ("main.py", "new main"),
        ("comfy/added_upstream.py", "new code"),
        ("models/checkpoints/put_checkpoints_here", ""),
        ("models/new_kind/put_new_kind_here", ""),
        ("custom_nodes/websocket_image_save.py", "new sample"),
        ("input/example.png", "release example"),
        ("output/_output_images_will_be_put_here", ""),
    ];

    /// A used install whose release recorded its names when installed.
    fn used_source(root: &Path) -> PathBuf {
        let source = legacy_used_source(root);
        fs::write(
            source.join(RELEASE_RECORD),
            "__pycache__\ncomfy\ndropped_upstream.py\nmain.py\n",
        )
        .expect("write release record");
        source
    }

    /// The same install from before the release record existed.
    fn legacy_used_source(root: &Path) -> PathBuf {
        let source = root.join("source");
        write(&source, &OLD_RELEASE);
        write(&source, &USER_FILES);
        write(&source, &UNKNOWN_FILES);
        source
    }

    fn new_release(root: &Path) -> PathBuf {
        let tree = root.join("extract").join("ComfyUI-master");
        write(&tree, &NEW_RELEASE);
        tree
    }

    fn assert_user_files_intact(source: &Path) {
        for (relative, contents) in USER_FILES.iter().chain(&UNKNOWN_FILES) {
            assert_eq!(
                read(&source.join(relative)).as_deref(),
                Some(*contents),
                "{relative} is not the release's and must be left as it was"
            );
        }
    }

    fn assert_new_release_installed(source: &Path) {
        assert_eq!(read(&source.join("main.py")).as_deref(), Some("new main"));
        assert!(source.join("comfy/added_upstream.py").is_file());
        assert!(
            !source.join("comfy/dropped_file.py").exists(),
            "code the new release no longer ships must not linger"
        );
        assert!(source.join("models/new_kind/put_new_kind_here").is_file());
        assert!(source.join("input/example.png").is_file());
        assert!(
            !source.join(SWAP_MARKER).exists(),
            "a finished swap leaves no marker"
        );
        assert_eq!(
            read(&source.join(RELEASE_RECORD)).as_deref(),
            Some("comfy\nmain.py"),
            "the record names what the installed release shipped"
        );
    }

    fn all_preserved_present() -> Vec<&'static str> {
        PRESERVED_SOURCE_ENTRIES.to_vec()
    }

    #[test]
    fn swap_replaces_release_code_and_leaves_everything_else_in_place() -> Result<()> {
        let dir = TestDir::new("basic");
        let source = used_source(&dir.0);
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        assert_new_release_installed(&source);
        assert_user_files_intact(&source);
        assert!(
            !source.join("dropped_upstream.py").exists(),
            "a top-level file the old release shipped and the new one dropped is removed"
        );
        assert!(!source.join("__pycache__").exists());
        assert_eq!(report.kept, all_preserved_present());
        assert_eq!(report.left_in_place, UNKNOWN_NAMES);
        assert!(report.warnings.is_empty(), "{:?}", report.warnings);
        Ok(())
    }

    /// Without a release record, only names the new release ships are
    /// treated as the release's: a top-level file the old release had and
    /// the new one dropped is reported as left in place rather than guessed.
    #[test]
    fn install_from_before_the_record_removes_only_what_the_new_release_ships() -> Result<()> {
        let dir = TestDir::new("legacy");
        let source = legacy_used_source(&dir.0);
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        assert_new_release_installed(&source);
        assert_user_files_intact(&source);
        assert_eq!(
            read(&source.join("dropped_upstream.py")).as_deref(),
            Some("old code")
        );
        let mut expected: Vec<&str> = UNKNOWN_NAMES.to_vec();
        expected.push("dropped_upstream.py");
        expected.sort_unstable();
        assert_eq!(report.left_in_place, expected);
        Ok(())
    }

    #[test]
    fn kept_lists_only_entries_the_install_already_had() -> Result<()> {
        let dir = TestDir::new("kept-subset");
        let source = dir.0.join("source");
        write(
            &source,
            &[
                ("main.py", "old main"),
                ("models/mine.safetensors", "user model"),
            ],
        );
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        // The release ships custom_nodes/, input/ and output/; they are now
        // there, but they were not the user's, so they were not "kept".
        assert_eq!(report.kept, ["models"]);
        assert!(
            source
                .join("output/_output_images_will_be_put_here")
                .is_file()
        );
        assert_eq!(
            read(&source.join("models/mine.safetensors")).as_deref(),
            Some("user model")
        );
        Ok(())
    }

    #[test]
    fn fresh_install_moves_the_release_into_place_with_its_record() -> Result<()> {
        let dir = TestDir::new("fresh");
        let source = dir.0.join("app").join("source");
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        assert_eq!(report, SwapReport::default());
        assert_eq!(read(&source.join("main.py")).as_deref(), Some("new main"));
        assert_eq!(
            read(&source.join(RELEASE_RECORD)).as_deref(),
            Some("comfy\nmain.py")
        );
        assert!(!tree.exists());
        Ok(())
    }

    /// Stops the swap before each filesystem change in turn — the way a crash
    /// or a kill would, with nothing cleaning up after it — then runs the swap
    /// again from a freshly unpacked release, as `--reinstall` would. Every
    /// interruption point must converge on a complete tree, with the user's
    /// files never touched in between, and `main.py` must never be present
    /// in a tree whose swap is unfinished.
    #[test]
    fn interrupted_swap_converges_when_run_again() -> Result<()> {
        let mut interrupted_at = 0;
        loop {
            let dir = TestDir::new("interrupt");
            let source = used_source(&dir.0);
            let tree = new_release(&dir.0);
            let mut steps = 0;
            let first = install_release_tree_with(&tree, &source, &mut |_| {
                steps += 1;
                if steps > interrupted_at {
                    Err(io::Error::other("interrupted"))
                } else {
                    Ok(())
                }
            });
            if first.is_ok() {
                assert!(interrupted_at > 0, "the swap took no steps");
                break;
            }
            assert_user_files_intact(&source);
            let left_marker = swap_interrupted(&source);
            if left_marker && read(&source.join("main.py")).as_deref() == Some("new main") {
                // Only the bookkeeping after it can be missing: main.py is the
                // last release entry moved in.
                assert!(
                    source.join("comfy/added_upstream.py").is_file()
                        && source.join("models/new_kind/put_new_kind_here").is_file(),
                    "step {interrupted_at}: the new main.py arrived before the rest of the release"
                );
            }

            let rerun_tree = dir.0.join("extract-2").join("ComfyUI-master");
            write(&rerun_tree, &NEW_RELEASE);
            let report = install_release_tree(&rerun_tree, &source)?;

            assert_user_files_intact(&source);
            assert_new_release_installed(&source);
            assert_eq!(
                report.kept,
                all_preserved_present(),
                "after an interruption at step {interrupted_at}, kept must still name what the user had"
            );
            assert_eq!(report.left_in_place, UNKNOWN_NAMES, "step {interrupted_at}");
            assert!(
                left_marker || interrupted_at == 0,
                "an interrupted swap must leave its marker (step {interrupted_at})"
            );
            interrupted_at += 1;
        }
        Ok(())
    }

    /// Once the swap has started, `main.py` is gone until the swap finishes.
    #[test]
    fn main_py_is_removed_first_and_moved_in_last() -> Result<()> {
        let dir = TestDir::new("entry-point-order");
        let source = used_source(&dir.0);
        let tree = new_release(&dir.0);
        let mut changes = Vec::new();

        install_release_tree_with(&tree, &source, &mut |path| {
            changes.push(path.to_path_buf());
            Ok(())
        })?;

        let release_changes: Vec<_> = changes
            .iter()
            .filter(|path| {
                !path
                    .file_name()
                    .is_some_and(|name| name.to_string_lossy().starts_with(CLI_FILE_PREFIX))
            })
            .collect();
        let main = source.join("main.py");
        assert_eq!(release_changes.first(), Some(&&main), "{changes:?}");
        assert_eq!(release_changes.last(), Some(&&main), "{changes:?}");
        Ok(())
    }

    /// The marker records what the user had before the swap began, so a
    /// re-run does not report as "kept" a folder the interrupted run added.
    #[test]
    fn rerun_reports_what_the_user_had_not_what_the_release_added() -> Result<()> {
        let dir = TestDir::new("interrupt-kept");
        let source = dir.0.join("source");
        write(
            &source,
            &[("main.py", "old main"), ("models/mine.ckpt", "m")],
        );
        let tree = new_release(&dir.0);
        // Let the whole swap run except removing the marker.
        let marker = source.join(SWAP_MARKER);
        let interrupted = install_release_tree_with(&tree, &source, &mut |path| {
            if path == marker && marker.exists() {
                Err(io::Error::other("interrupted"))
            } else {
                Ok(())
            }
        });
        assert!(interrupted.is_err());
        assert!(source.join("output").exists(), "the release added output/");
        assert_eq!(planned_kept(&source), ["models"]);

        let rerun_tree = dir.0.join("extract-2").join("ComfyUI-master");
        write(&rerun_tree, &NEW_RELEASE);
        let report = install_release_tree(&rerun_tree, &source)?;

        assert_eq!(report.kept, ["models"]);
        Ok(())
    }

    /// An unreadable marker does not stop the swap from finishing: it only
    /// feeds the report, which then says so.
    #[test]
    fn unreadable_marker_finishes_with_a_warning() -> Result<()> {
        let dir = TestDir::new("bad-marker");
        let source = used_source(&dir.0);
        // Present but not readable as text.
        fs::write(source.join(SWAP_MARKER), [0xff, 0xfe, 0xfd])?;
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        assert_new_release_installed(&source);
        assert_user_files_intact(&source);
        assert!(report.kept.is_empty());
        assert!(
            report
                .warnings
                .iter()
                .any(|warning| warning.contains("none of them was touched")),
            "{:?}",
            report.warnings
        );
        Ok(())
    }

    /// The user's files keep their inode and mtime, and neither they, the
    /// preserved folders nor `source/` itself see a ctime change — which a
    /// rename would cause. So nothing of the user's was moved, not merely
    /// moved back.
    #[cfg(unix)]
    #[test]
    fn user_content_is_never_moved_or_rewritten() -> Result<()> {
        use std::os::unix::fs::MetadataExt;

        let dir = TestDir::new("inode");
        let source = used_source(&dir.0);
        let tree = new_release(&dir.0);
        let paths: Vec<PathBuf> = std::iter::once(source.clone())
            .chain(
                USER_FILES
                    .iter()
                    .chain(&UNKNOWN_FILES)
                    .map(|(relative, _)| source.join(relative)),
            )
            .chain(
                PRESERVED_SOURCE_ENTRIES
                    .iter()
                    .map(|name| source.join(name)),
            )
            .collect();
        let identity = |path: &PathBuf| {
            let metadata = fs::symlink_metadata(path).expect("user path");
            (
                metadata.ino(),
                metadata.mtime(),
                metadata.mtime_nsec(),
                metadata.ctime(),
                metadata.ctime_nsec(),
            )
        };
        let before: Vec<_> = paths.iter().map(identity).collect();
        // Let a ctime change, if one happened, land on a different tick.
        std::thread::sleep(std::time::Duration::from_millis(20));

        install_release_tree(&tree, &source)?;

        for (path, before) in paths.iter().zip(before) {
            let after = identity(path);
            if path == &source
                || PRESERVED_SOURCE_ENTRIES
                    .iter()
                    .any(|name| path.ends_with(name))
            {
                // Folders the release adds into get a new mtime/ctime from
                // that; only the inode shows whether they were moved.
                assert_eq!(before.0, after.0, "{} was replaced", path.display());
            } else {
                assert_eq!(before, after, "{} was moved or rewritten", path.display());
            }
        }
        assert_user_files_intact(&source);
        Ok(())
    }

    /// `models` is a symlink to a folder elsewhere (a bigger disk). It stays a
    /// symlink, the folder behind it is not written into, and nothing in it
    /// is copied or removed.
    #[cfg(unix)]
    #[test]
    fn symlinked_models_folder_is_left_alone() -> Result<()> {
        let dir = TestDir::new("symlinked-models");
        let elsewhere = dir.0.join("big-disk").join("models");
        write(&elsewhere, &[("checkpoints/huge.safetensors", "huge")]);
        let source = dir.0.join("source");
        write(&source, &[("main.py", "old main")]);
        std::os::unix::fs::symlink(&elsewhere, source.join("models"))?;
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        assert!(
            fs::symlink_metadata(source.join("models"))?
                .file_type()
                .is_symlink()
        );
        assert_eq!(fs::read_link(source.join("models"))?, elsewhere);
        let mut entries: Vec<_> = fs::read_dir(&elsewhere)?
            .map(|entry| entry.map(|entry| entry.file_name()))
            .collect::<io::Result<_>>()?;
        entries.sort();
        assert_eq!(entries, ["checkpoints"], "the release wrote into the link");
        assert_eq!(
            read(&elsewhere.join("checkpoints/huge.safetensors")).as_deref(),
            Some("huge")
        );
        assert!(report.kept.contains(&"models"));
        Ok(())
    }

    /// A symlink inside `models` (one model folder on another disk, or a link
    /// that has gone dangling) is left exactly as it is.
    #[cfg(unix)]
    #[test]
    fn symlinks_inside_models_are_left_alone() -> Result<()> {
        let dir = TestDir::new("symlink-inside-models");
        let elsewhere = dir.0.join("big-disk").join("checkpoints");
        write(&elsewhere, &[("huge.safetensors", "huge")]);
        let source = dir.0.join("source");
        write(&source, &[("main.py", "old main")]);
        fs::create_dir_all(source.join("models"))?;
        std::os::unix::fs::symlink(&elsewhere, source.join("models/checkpoints"))?;
        std::os::unix::fs::symlink(dir.0.join("gone"), source.join("models/dangling"))?;
        // A loop must not be followed either.
        std::os::unix::fs::symlink(source.join("models"), source.join("models/loop"))?;
        let tree = new_release(&dir.0);

        install_release_tree(&tree, &source)?;

        assert_eq!(fs::read_link(source.join("models/checkpoints"))?, elsewhere);
        assert_eq!(
            fs::read_link(source.join("models/dangling"))?,
            dir.0.join("gone")
        );
        assert_eq!(
            fs::read_link(source.join("models/loop"))?,
            source.join("models")
        );
        assert!(
            !elsewhere.join("put_checkpoints_here").exists(),
            "the release's placeholder must not be written through the link"
        );
        assert!(source.join("models/new_kind/put_new_kind_here").is_file());
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn copy_fallback_recreates_symlinks_instead_of_following_them() -> Result<()> {
        let dir = TestDir::new("copy-no-follow");
        let from = dir.0.join("from");
        write(&from, &[("a/file.txt", "a")]);
        std::os::unix::fs::symlink(dir.0.join("outside"), from.join("a/link"))?;
        std::os::unix::fs::symlink(&from, from.join("a/loop"))?;

        copy_tree_no_follow(&from, &dir.0.join("to"))?;

        assert_eq!(read(&dir.0.join("to/a/file.txt")).as_deref(), Some("a"));
        assert_eq!(
            fs::read_link(dir.0.join("to/a/link"))?,
            dir.0.join("outside")
        );
        assert_eq!(fs::read_link(dir.0.join("to/a/loop"))?, from);
        Ok(())
    }

    /// A copy that a crash cut short only ever exists under a temporary
    /// name, which the next swap removes.
    #[test]
    fn leftover_copy_in_progress_is_removed_not_reported() -> Result<()> {
        let dir = TestDir::new("copy-leftover");
        let source = used_source(&dir.0);
        write(&source, &[(".rocm-cli-copy-main.py", "trunc")]);
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        assert!(!source.join(".rocm-cli-copy-main.py").exists());
        assert_eq!(report.left_in_place, UNKNOWN_NAMES);
        Ok(())
    }

    #[test]
    fn a_failed_release_move_is_an_error_not_a_copy() -> Result<()> {
        let dir = TestDir::new("move-error");
        let to = dir.0.join("to");
        // The source does not exist: a NotFound rename error must surface
        // as an error, not fall back to copying.
        let error = move_release_entry(&dir.0.join("missing"), &to, &mut |_| Ok(()))
            .expect_err("a failed rename that does not cross devices must fail");
        assert!(format!("{error:#}").contains("failed to move"), "{error:#}");
        assert!(!to.exists());
        Ok(())
    }

    /// The used install, plus a folder of the user's that the next release
    /// starts shipping under the same name.
    fn used_source_with_colliding_entry(root: &Path) -> PathBuf {
        let source = used_source(root);
        write(&source, &[("app/settings.json", "user app")]);
        source
    }

    fn new_release_adding_app(root: &Path, folder: &str) -> PathBuf {
        let tree = root.join(folder).join("ComfyUI-master");
        write(&tree, &NEW_RELEASE);
        write(&tree, &[("app/__init__.py", "new app")]);
        tree
    }

    /// Where the user's `app/` is now: its own name or a set-aside one.
    fn user_app_locations(source: &Path) -> Vec<String> {
        let mut found: Vec<String> = fs::read_dir(source)
            .expect("read source")
            .map(|entry| {
                entry
                    .expect("entry")
                    .file_name()
                    .to_string_lossy()
                    .into_owned()
            })
            .filter(|name| {
                read(&source.join(name).join("settings.json")).as_deref() == Some("user app")
            })
            .collect();
        found.sort();
        found
    }

    /// An entry of the user's that has the name of something the new release
    /// adds is renamed, never deleted, and reported with its new name; the
    /// release's entry of that name is installed.
    #[test]
    fn user_entry_named_like_new_release_code_is_set_aside() -> Result<()> {
        let dir = TestDir::new("set-aside");
        let source = used_source_with_colliding_entry(&dir.0);
        let tree = new_release_adding_app(&dir.0, "extract");

        let report = install_release_tree(&tree, &source)?;

        let [(name, new_name)] = report.set_aside.as_slice() else {
            panic!("expected one entry set aside: {report:?}");
        };
        assert_eq!(name, "app");
        assert!(
            new_name.starts_with(&format!("app{SET_ASIDE_INFIX}")),
            "{new_name}"
        );
        assert_eq!(
            read(&source.join(new_name).join("settings.json")).as_deref(),
            Some("user app"),
            "the reported new name holds the user's files"
        );
        assert_eq!(user_app_locations(&source), std::slice::from_ref(new_name));
        assert_eq!(
            read(&source.join("app/__init__.py")).as_deref(),
            Some("new app")
        );
        assert_user_files_intact(&source);
        assert!(report.replaced.is_empty(), "{:?}", report.replaced);
        assert_eq!(report.left_in_place, UNKNOWN_NAMES);
        assert_eq!(
            read(&source.join(RELEASE_RECORD)).as_deref(),
            Some("app\ncomfy\nmain.py")
        );
        // The next reinstall knows `app` is the release's, and lists the
        // user's renamed folder as theirs.
        let again = install_release_tree(&new_release_adding_app(&dir.0, "extract-2"), &source)?;
        assert!(again.set_aside.is_empty(), "{again:?}");
        assert!(again.left_in_place.contains(new_name), "{again:?}");
        assert_eq!(user_app_locations(&source), std::slice::from_ref(new_name));
        Ok(())
    }

    /// Stopping the swap at every point (see
    /// `interrupted_swap_converges_when_run_again`) with an entry to set
    /// aside: the user's folder is at its own name or its set-aside name,
    /// never both and never gone, and a re-run neither deletes it nor sets
    /// aside the release's own entry that the interrupted run moved in.
    #[test]
    fn interrupted_set_aside_converges_when_run_again() -> Result<()> {
        let mut interrupted_at = 0;
        loop {
            let dir = TestDir::new("interrupt-set-aside");
            let source = used_source_with_colliding_entry(&dir.0);
            let tree = new_release_adding_app(&dir.0, "extract");
            let mut steps = 0;
            let first = install_release_tree_with(&tree, &source, &mut |_| {
                steps += 1;
                if steps > interrupted_at {
                    Err(io::Error::other("interrupted"))
                } else {
                    Ok(())
                }
            });
            if first.is_ok() {
                break;
            }
            assert_eq!(
                user_app_locations(&source).len(),
                1,
                "step {interrupted_at}: the user's app/ must be in exactly one place"
            );

            let report =
                install_release_tree(&new_release_adding_app(&dir.0, "extract-2"), &source)?;

            let locations = user_app_locations(&source);
            assert_eq!(locations.len(), 1, "step {interrupted_at}: {locations:?}");
            assert_eq!(
                report.set_aside,
                [("app".to_owned(), locations[0].clone())],
                "step {interrupted_at}"
            );
            assert_eq!(
                read(&source.join("app/__init__.py")).as_deref(),
                Some("new app"),
                "step {interrupted_at}"
            );
            assert_user_files_intact(&source);
            assert_eq!(report.left_in_place, UNKNOWN_NAMES, "step {interrupted_at}");
            interrupted_at += 1;
        }
        assert!(interrupted_at > 0, "the swap took no steps");
        Ok(())
    }

    /// A new release adds `app/`, which the user does not have. Wherever the
    /// swap is stopped, a re-run treats an `app/` the interrupted run already
    /// moved in as release code (the marker names that run's release), not
    /// as the user's: nothing is set aside.
    #[test]
    fn rerun_does_not_set_aside_code_the_interrupted_run_moved_in() -> Result<()> {
        let mut interrupted_at = 0;
        loop {
            let dir = TestDir::new("interrupt-new-name");
            let source = used_source(&dir.0);
            let tree = new_release_adding_app(&dir.0, "extract");
            let mut steps = 0;
            let first = install_release_tree_with(&tree, &source, &mut |_| {
                steps += 1;
                if steps > interrupted_at {
                    Err(io::Error::other("interrupted"))
                } else {
                    Ok(())
                }
            });
            if first.is_ok() {
                break;
            }

            let report =
                install_release_tree(&new_release_adding_app(&dir.0, "extract-2"), &source)?;

            assert!(
                report.set_aside.is_empty(),
                "step {interrupted_at}: {report:?}"
            );
            assert_eq!(report.left_in_place, UNKNOWN_NAMES, "step {interrupted_at}");
            assert_eq!(
                read(&source.join("app/__init__.py")).as_deref(),
                Some("new app"),
                "step {interrupted_at}"
            );
            assert_user_files_intact(&source);
            interrupted_at += 1;
        }
        assert!(interrupted_at > 0, "the swap took no steps");
        Ok(())
    }

    /// Without a record nothing tells the user's entry from release code of
    /// the same name, so it is replaced, and the report lists every entry that
    /// went.
    #[test]
    fn install_from_before_the_record_lists_what_it_replaced() -> Result<()> {
        let dir = TestDir::new("legacy-replaced");
        let source = legacy_used_source(&dir.0);
        write(&source, &[("app/settings.json", "user app")]);
        let tree = new_release_adding_app(&dir.0, "extract");

        let report = install_release_tree(&tree, &source)?;

        assert_eq!(report.replaced, ["__pycache__", "app", "comfy", "main.py"]);
        assert!(report.set_aside.is_empty(), "{report:?}");
        assert!(user_app_locations(&source).is_empty());
        assert_user_files_intact(&source);
        Ok(())
    }

    /// An unreadable record does not stop the swap: it falls back to the new
    /// release's names, lists what that replaced, and says why.
    #[test]
    fn unreadable_record_falls_back_to_the_new_release_names_with_a_warning() -> Result<()> {
        let dir = TestDir::new("bad-record");
        let source = used_source(&dir.0);
        // Present but not readable as text.
        fs::write(source.join(RELEASE_RECORD), [0xff, 0xfe, 0xfd])?;
        let tree = new_release(&dir.0);

        let report = install_release_tree(&tree, &source)?;

        assert_new_release_installed(&source);
        assert_user_files_intact(&source);
        // Only the record named it, so without the record it stays.
        assert_eq!(
            read(&source.join("dropped_upstream.py")).as_deref(),
            Some("old code")
        );
        assert!(
            report
                .left_in_place
                .contains(&"dropped_upstream.py".to_owned())
        );
        assert_eq!(report.replaced, ["__pycache__", "comfy", "main.py"]);
        assert!(
            report.warnings.iter().any(|warning| {
                warning.contains(&format!(
                    "could not read {}",
                    source.join(RELEASE_RECORD).display()
                )) && warning.contains("the names the new release ships were replaced")
            }),
            "{:?}",
            report.warnings
        );
        Ok(())
    }

    /// A record line that is not the name of one entry of `source/` is
    /// ignored and reported, never followed out of the folder.
    #[test]
    fn release_record_lines_that_are_not_a_single_entry_are_ignored() -> Result<()> {
        let dir = TestDir::new("record-lines");
        let source = dir.0.join("source");
        fs::create_dir_all(&source)?;
        fs::write(
            source.join(RELEASE_RECORD),
            "..\n/abs\na/b\n.\n\nmain.py\nmodels\ncomfy\n",
        )?;

        let (names, warnings) = read_release_record(&source);

        assert_eq!(
            names,
            Some(vec![OsString::from("main.py"), OsString::from("comfy")]),
            "only single entry names, and never a preserved one"
        );
        assert_eq!(warnings.len(), 4, "{warnings:?}");
        for line in ["\"..\"", "\"/abs\"", "\"a/b\"", "\".\""] {
            assert!(
                warnings
                    .iter()
                    .any(|warning| warning.starts_with(&format!("ignored {line}"))),
                "{line}: {warnings:?}"
            );
        }
        Ok(())
    }

    /// A release entry that cannot be removed stops the swap with
    /// [`RemovalFailed`] naming it, leaving the marker that makes `start`
    /// refuse; once it can be removed, running the swap again finishes it.
    /// The removal is made to fail by injection rather than by permissions,
    /// which do not stop a test running as root.
    #[test]
    fn an_entry_that_cannot_be_removed_stops_the_swap_with_a_typed_error() -> Result<()> {
        let dir = TestDir::new("cannot-remove");
        let source = used_source(&dir.0);
        let locked = source.join("comfy");
        let held = |path: &Path| {
            if path == locked {
                Err(io::Error::from(io::ErrorKind::PermissionDenied))
            } else {
                remove_path_io(path)
            }
        };

        let error = install_release_tree_removing_with(
            &new_release(&dir.0),
            &source,
            &mut |_| Ok(()),
            &held,
        )
        .expect_err("a release entry that cannot be removed must stop the swap");

        let failed = error
            .downcast_ref::<RemovalFailed>()
            .unwrap_or_else(|| panic!("expected RemovalFailed, got {error:#}"));
        assert_eq!(failed.path, locked);
        assert!(
            format!("{error:#}").contains("close any program using it"),
            "{error:#}"
        );
        assert!(swap_interrupted(&source));
        assert!(
            locked.is_dir(),
            "the entry that could not be removed is still there"
        );
        assert_user_files_intact(&source);

        let rerun_tree = dir.0.join("extract-2").join("ComfyUI-master");
        write(&rerun_tree, &NEW_RELEASE);
        let report = install_release_tree(&rerun_tree, &source)?;
        assert_new_release_installed(&source);
        assert_user_files_intact(&source);
        assert_eq!(report.kept, all_preserved_present());
        Ok(())
    }

    /// Marker lines that do not name a single entry of `source/` are dropped
    /// when the marker is read, for the release's names and for set-aside
    /// pairs alike.
    #[test]
    fn marker_lines_that_are_not_a_single_entry_are_ignored() {
        let plan = SwapPlan::parse(
            "models\n\
             release\t..\n\
             release\t/abs\n\
             release\ta/b\n\
             release\t.\n\
             release\t\n\
             release\tmain.py\n\
             set-aside\t../outside\tx\n\
             set-aside\tapp\t../escaped\n\
             set-aside\t/abs\tx\n\
             set-aside\tapp\ta/b\n\
             set-aside\tapp\tapp.rocm-cli-kept-1",
        );

        assert_eq!(plan.kept, ["models"]);
        assert_eq!(
            plan.release.into_iter().collect::<Vec<_>>(),
            [OsString::from("main.py")]
        );
        assert_eq!(
            plan.set_aside,
            [(OsString::from("app"), OsString::from("app.rocm-cli-kept-1"))]
        );
    }

    /// An interrupted swap's marker naming paths outside `source/` (damaged or
    /// tampered with) never makes a re-run move anything outside it.
    #[test]
    fn a_marker_naming_paths_outside_the_folder_moves_nothing_outside_it() -> Result<()> {
        let dir = TestDir::new("marker-escape");
        let source = used_source_with_colliding_entry(&dir.0);
        write(&dir.0, &[("outside/precious.txt", "outside")]);
        fs::write(
            source.join(SWAP_MARKER),
            "set-aside\t../outside\tmoved-in\n\
             set-aside\tapp\t../escaped\n\
             release\t../outside",
        )?;

        install_release_tree(&new_release(&dir.0), &source)?;

        assert_eq!(
            read(&dir.0.join("outside/precious.txt")).as_deref(),
            Some("outside")
        );
        assert!(!source.join("moved-in").exists());
        assert!(!dir.0.join("escaped").exists());
        assert_eq!(user_app_locations(&source), ["app"]);
        assert_user_files_intact(&source);
        Ok(())
    }

    /// The name a set-aside entry gets skips names already taken in the
    /// folder and names this swap already gave another entry.
    #[test]
    fn set_aside_name_skips_names_already_taken() {
        let dir = TestDir::new("set-aside-name");
        let source = dir.0.join("source");
        write(
            &source,
            &[
                ("app.rocm-cli-kept-100", "earlier"),
                ("app.rocm-cli-kept-100-2/file", "earlier"),
            ],
        );
        let plan = SwapPlan {
            set_aside: vec![(
                OsString::from("app"),
                OsString::from("app.rocm-cli-kept-100-3"),
            )],
            ..SwapPlan::default()
        };

        assert_eq!(
            set_aside_name(&source, OsStr::new("app"), &plan, 100),
            "app.rocm-cli-kept-100-4"
        );
        assert_eq!(
            set_aside_name(&source, OsStr::new("app"), &SwapPlan::default(), 101),
            "app.rocm-cli-kept-101"
        );
    }

    fn crosses_devices_once(first: &Path) -> impl Fn(&Path, &Path) -> io::Result<()> + use<'_> {
        move |from: &Path, to: &Path| {
            if from == first {
                Err(io::Error::from(io::ErrorKind::CrossesDevices))
            } else {
                fs::rename(from, to)
            }
        }
    }

    /// When the release cannot be renamed into place because `source` is on
    /// another filesystem, it is copied to a temporary name (replacing a copy
    /// a crash left there), renamed into place once complete, and the staged
    /// original is removed.
    #[test]
    fn a_move_across_filesystems_copies_under_a_temporary_name() -> Result<()> {
        let dir = TestDir::new("cross-device");
        let from = dir.0.join("extract").join("comfy");
        write(&from, &[("a.py", "new code"), ("sub/b.py", "more code")]);
        let into = dir.0.join("source").join("models");
        // What a copy cut short by a crash left behind.
        write(&into, &[(".rocm-cli-copy-comfy/a.py", "trunc")]);
        let to = into.join("comfy");

        move_release_entry_with(&from, &to, &mut |_| Ok(()), &crosses_devices_once(&from))?;

        assert_eq!(read(&to.join("a.py")).as_deref(), Some("new code"));
        assert_eq!(read(&to.join("sub/b.py")).as_deref(), Some("more code"));
        assert!(!from.exists(), "the staged original is removed once copied");
        assert!(!into.join(".rocm-cli-copy-comfy").exists());
        Ok(())
    }

    /// A copy that fails part-way removes its temporary copy and leaves the
    /// target name free. A socket cannot be copied, whoever runs the test.
    #[cfg(unix)]
    #[test]
    fn a_failed_copy_across_filesystems_leaves_no_temporary_copy() -> Result<()> {
        let dir = TestDir::new("cross-device-fail");
        let from = dir.0.join("extract").join("comfy");
        write(&from, &[("a.py", "new code")]);
        let _socket = std::os::unix::net::UnixListener::bind(from.join("z.sock"))?;
        let into = dir.0.join("source");
        fs::create_dir_all(&into)?;
        let to = into.join("comfy");

        move_release_entry_with(&from, &to, &mut |_| Ok(()), &crosses_devices_once(&from))
            .expect_err("a socket cannot be copied");

        assert!(!to.exists());
        assert!(
            !into.join(".rocm-cli-copy-comfy").exists(),
            "the partial copy must be removed"
        );
        assert_eq!(read(&from.join("a.py")).as_deref(), Some("new code"));
        Ok(())
    }

    /// On Windows a file another program opened without sharing cannot be
    /// renamed (`ERROR_SHARING_VIOLATION`); the rename is retried until that
    /// program closes it.
    #[cfg(windows)]
    #[test]
    fn rename_waits_for_a_program_holding_the_file() -> Result<()> {
        use std::os::windows::fs::OpenOptionsExt;

        let dir = TestDir::new("held-file");
        let from = dir.0.join("held.py");
        let to = dir.0.join("moved.py");
        fs::write(&from, "code")?;
        let held = fs::OpenOptions::new()
            .read(true)
            .share_mode(0)
            .open(&from)?;
        let error = fs::rename(&from, &to).expect_err("the file is held without sharing");
        assert!(is_held_by_another_program(&error), "{error:?}");
        let release = std::thread::spawn(move || {
            std::thread::sleep(std::time::Duration::from_millis(120));
            drop(held);
        });

        rename_with_retry(&from, &to)?;

        release.join().expect("release thread");
        assert_eq!(read(&to).as_deref(), Some("code"));
        Ok(())
    }
}
