//! Repository task runner.
//!
//! Currently provides the release-artifact signing toolchain in pure Rust so the
//! project's signing, CI verification, and test keygen no longer depend on the
//! `openssl` CLI. Run via the workspace alias `cargo xtask <command>`.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command as ProcessCommand, ExitCode};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use rocm_core::{
    generate_rsa_signing_keypair, sign_rsa_pkcs1_sha256_signature,
    verify_rsa_pkcs1_sha256_signature,
};
use serde::Deserialize;

#[derive(Parser)]
#[command(name = "xtask", about = "rocm-cli repository tasks")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Generate a 2048-bit RSA signing keypair (PKCS#8 private + SPKI public PEM).
    Keygen {
        /// Path to write the PKCS#8 private-key PEM.
        #[arg(long)]
        private_out: PathBuf,
        /// Path to write the SubjectPublicKeyInfo public-key PEM.
        #[arg(long)]
        public_out: PathBuf,
    },
    /// Sign a file with an RSA private key (RSASSA-PKCS#1 v1.5 over SHA-256).
    Sign {
        /// Path to the PKCS#8 private-key PEM.
        #[arg(long)]
        private_key: PathBuf,
        /// File whose contents are signed.
        #[arg(long = "in")]
        input: PathBuf,
        /// Path to write the raw signature bytes.
        #[arg(long = "out")]
        output: PathBuf,
    },
    /// Verify a file's signature against an RSA public key.
    Verify {
        /// Path to the SubjectPublicKeyInfo public-key PEM.
        #[arg(long)]
        public_key: PathBuf,
        /// File whose signature is checked.
        #[arg(long = "in")]
        input: PathBuf,
        /// Path to the raw signature bytes.
        #[arg(long)]
        signature: PathBuf,
    },
    /// Regenerate the Cargo dependency table in MANIFEST.md from `cargo metadata`.
    Manifest {
        /// Verify the table is up to date without writing; exit non-zero if it would change.
        #[arg(long)]
        check: bool,
    },
}

/// Marker comments bracketing the generated dependency table in MANIFEST.md.
const MANIFEST_BEGIN: &str =
    "<!-- BEGIN CARGO DEPENDENCIES (generated by `cargo xtask manifest`; do not edit by hand) -->";
const MANIFEST_END: &str = "<!-- END CARGO DEPENDENCIES -->";

/// Subset of the `cargo metadata` JSON output we care about.
#[derive(Deserialize)]
struct Metadata {
    workspace_root: String,
    packages: Vec<Package>,
}

/// Subset of a single package entry from `cargo metadata`.
#[derive(Deserialize)]
struct Package {
    name: String,
    version: String,
    /// `None` for workspace members; `Some(_)` for external (registry/git) deps.
    source: Option<String>,
    /// `None` when the crate declares no SPDX license expression.
    license: Option<String>,
}

/// Run `cargo metadata` and deserialize the parts we need.
fn load_metadata() -> Result<Metadata> {
    let output = ProcessCommand::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()))
        .args(["metadata", "--format-version", "1", "--locked"])
        .output()
        .context("failed to run `cargo metadata`")?;
    if !output.status.success() {
        bail!(
            "`cargo metadata` failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    serde_json::from_slice(&output.stdout).context("failed to parse `cargo metadata` output")
}

/// Build the markdown dependency table (header, separator, and one row per
/// external dependency, sorted ascending by name then version).
fn render_dependency_table(metadata: &Metadata) -> String {
    use std::fmt::Write as _;

    let mut rows: Vec<(&str, &str, &str)> = metadata
        .packages
        .iter()
        .filter(|pkg| pkg.source.is_some())
        .map(|pkg| {
            (
                pkg.name.as_str(),
                pkg.version.as_str(),
                pkg.license.as_deref().unwrap_or("UNKNOWN"),
            )
        })
        .collect();
    rows.sort_unstable();

    let mut table = String::from("| Crate | Version | License |\n|-------|---------|---------|\n");
    for (name, version, license) in rows {
        // Writing to a String is infallible.
        let _ = writeln!(table, "| {name} | {version} | {license} |");
    }
    table
}

/// Replace the content between the BEGIN/END markers with `table`, preserving
/// the markers themselves and the surrounding document.
fn splice_table(manifest: &str, table: &str) -> Result<String> {
    let begin = manifest
        .find(MANIFEST_BEGIN)
        .with_context(|| format!("MANIFEST.md is missing the marker `{MANIFEST_BEGIN}`"))?;
    let end = manifest
        .find(MANIFEST_END)
        .with_context(|| format!("MANIFEST.md is missing the marker `{MANIFEST_END}`"))?;
    if end < begin {
        bail!("MANIFEST.md markers are out of order: END appears before BEGIN");
    }
    // `table` already ends with a newline, so the END marker lands on its own line.
    let before = &manifest[..begin + MANIFEST_BEGIN.len()];
    let after = &manifest[end + MANIFEST_END.len()..];
    Ok(format!("{before}\n{table}{MANIFEST_END}{after}"))
}

/// Regenerate (or, with `check`, verify) the dependency table in MANIFEST.md.
fn run_manifest(check: bool) -> Result<()> {
    let metadata = load_metadata()?;
    let manifest_path = Path::new(&metadata.workspace_root).join("MANIFEST.md");
    let current = fs::read_to_string(&manifest_path)
        .with_context(|| format!("failed to read {}", manifest_path.display()))?;
    let table = render_dependency_table(&metadata);
    let updated = splice_table(&current, &table)?;

    if check {
        if updated != current {
            bail!(
                "MANIFEST.md dependency table is out of date; run `cargo xtask manifest` to update it"
            );
        }
        return Ok(());
    }

    if updated != current {
        fs::write(&manifest_path, updated)
            .with_context(|| format!("failed to write {}", manifest_path.display()))?;
    }
    Ok(())
}

/// Write a private-key PEM, restricting it to owner-only (`0o600`) on Unix so the
/// key is never group- or world-readable. On Unix the file is created with the
/// restricted mode up front, and any pre-existing file is tightened too.
fn write_private_key(path: &Path, pem: &str) -> Result<()> {
    #[cfg(unix)]
    {
        use std::io::Write;
        use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(path)
            .with_context(|| format!("failed to write {}", path.display()))?;
        // `.mode()` only applies when creating the file; tighten an existing one too.
        file.set_permissions(std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("failed to restrict permissions on {}", path.display()))?;
        file.write_all(pem.as_bytes())
            .with_context(|| format!("failed to write {}", path.display()))?;
    }
    #[cfg(not(unix))]
    {
        fs::write(path, pem.as_bytes())
            .with_context(|| format!("failed to write {}", path.display()))?;
    }
    Ok(())
}

fn run() -> Result<()> {
    match Cli::parse().command {
        Command::Keygen {
            private_out,
            public_out,
        } => {
            let (private_pem, public_pem) = generate_rsa_signing_keypair()?;
            write_private_key(&private_out, &private_pem)?;
            fs::write(&public_out, public_pem.as_bytes())
                .with_context(|| format!("failed to write {}", public_out.display()))?;
        }
        Command::Sign {
            private_key,
            input,
            output,
        } => {
            let private_pem = fs::read_to_string(&private_key)
                .with_context(|| format!("failed to read {}", private_key.display()))?;
            let payload =
                fs::read(&input).with_context(|| format!("failed to read {}", input.display()))?;
            let signature = sign_rsa_pkcs1_sha256_signature(&private_pem, &payload)?;
            fs::write(&output, signature)
                .with_context(|| format!("failed to write {}", output.display()))?;
        }
        Command::Verify {
            public_key,
            input,
            signature,
        } => {
            let public_pem = fs::read_to_string(&public_key)
                .with_context(|| format!("failed to read {}", public_key.display()))?;
            let payload =
                fs::read(&input).with_context(|| format!("failed to read {}", input.display()))?;
            let signature_bytes = fs::read(&signature)
                .with_context(|| format!("failed to read {}", signature.display()))?;
            let label = input.display().to_string();
            verify_rsa_pkcs1_sha256_signature(&public_pem, &payload, &signature_bytes, &label)?;
        }
        Command::Manifest { check } => run_manifest(check)?,
    }
    Ok(())
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("error: {error:#}");
            ExitCode::FAILURE
        }
    }
}
