// Copyright Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: MIT

//! Build a tiny `libmpi_cxx.so.40` stub that defines the legacy OpenMPI C++
//! binding symbols PyTorch's ROCm wheels reference.
//!
//! OpenMPI 5.x removed the C++ bindings (`libmpi_cxx`), but the ROCm PyTorch
//! wheels were built against OpenMPI 4.x and their `libtorch_cpu.so` carries a
//! handful of undefined `MPI::*` symbols (e.g. `MPI::Datatype::Free()`). A bare
//! symlink to `libmpi.so` satisfies the `libmpi_cxx.so.40` soname but not those
//! symbols, so `import torch` fails with `undefined symbol: _ZN3MPI...`. The
//! symbols are never actually called in single-node serving, so a stub that
//! merely *defines* them lets the dynamic loader resolve torch. The stub is
//! compiled here (target-arch correct, no runtime toolchain needed) and embedded
//! via `include_bytes!`; `rocm_core::openmpi` materializes it at runtime.
//!
//! The C++ symbol names are valid C identifiers, so the stub is plain C with no
//! libstdc++ dependency; `-nostdlib` yields a self-contained object with no
//! `NEEDED` entries that loads on any Linux of the same architecture.

use std::env;
use std::fs;
use std::path::Path;

const STUB_SOURCE: &str = r"/* Auto-generated by rocm-core/build.rs.
 * Stubs for the legacy OpenMPI C++ bindings (libmpi_cxx) removed in OpenMPI 5.x.
 * PyTorch's libtorch_cpu.so references these but never calls them in single-node
 * serving; defining them lets the dynamic loader resolve `import torch`.
 * Itanium-ABI-mangled forms cover MPI::Win::Free(), MPI::Datatype::Free(), and
 * MPI::Comm::Comm() (C1/C2 ctors); ompi_mpi_cxx_op_intercept and
 * ompi_op_set_cxx_callback are the C reduction trampolines the OpenMPI 4.x C++
 * bindings exported. These are the complete set of `libmpi_cxx` symbols the ROCm
 * torch wheel needs that the OpenMPI 5.x C runtime (libmpi.so) does not
 * provide. */
void _ZN3MPI3Win4FreeEv(void) {}
void _ZN3MPI8Datatype4FreeEv(void) {}
void _ZN3MPI4CommC1Ev(void) {}
void _ZN3MPI4CommC2Ev(void) {}
void ompi_mpi_cxx_op_intercept(void) {}
void ompi_op_set_cxx_callback(void) {}
";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let stub_path = Path::new(&out_dir).join("libmpi_cxx_stub.so");

    // The stub is only consumed on Linux. Always emit a file so the Linux-only
    // `include_bytes!` always has something to read; an empty file disables the
    // shim gracefully.
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os != "linux" {
        let _ = fs::write(&stub_path, b"");
        return;
    }

    if let Err(reason) = build_stub(&out_dir, &stub_path) {
        let _ = fs::write(&stub_path, b"");
        println!(
            "cargo:warning=rocm-core: OpenMPI C++ bindings (libmpi_cxx) stub not built: {reason}; \
PyTorch may fail to import on hosts with OpenMPI 5.x"
        );
    }
}

fn build_stub(out_dir: &str, stub_path: &Path) -> Result<(), String> {
    let src_path = Path::new(out_dir).join("libmpi_cxx_stub.c");
    fs::write(&src_path, STUB_SOURCE).map_err(|error| format!("write source: {error}"))?;

    let compiler = cc::Build::new()
        .try_get_compiler()
        .map_err(|error| format!("no C compiler: {error}"))?;

    let status = compiler
        .to_command()
        .arg("-shared")
        .arg("-fPIC")
        .arg("-nostdlib")
        .arg("-Wl,-soname,libmpi_cxx.so.40")
        .arg("-o")
        .arg(stub_path)
        .arg(&src_path)
        .status()
        .map_err(|error| format!("spawn compiler: {error}"))?;

    if !status.success() {
        return Err(format!("compiler exited with {status}"));
    }
    if !stub_path.exists() {
        return Err("compiler produced no output".to_owned());
    }
    Ok(())
}
